# Generated by Django 5.0.3 on 2024-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='cv'),
        ),
    ]
